#!/usr/bin/env tsx
/**
 * Update Addresses Script
 *
 * Updates token addresses in SDK and deployment configs after contract deployment.
 *
 * Usage:
 *   npx tsx scripts/update-addresses.ts
 */

import * as fs from "fs";
import * as path from "path";

// Update this map with deployed addresses
const DEPLOYED_ADDRESSES: Record<
  string,
  { polygonAddress: string; nttManager: string; custodyAccount: string }
> = {
  // TODO: Fill in after deployment
  // spacex: {
  //   polygonAddress: "0x...",
  //   nttManager: "0x...",
  //   custodyAccount: "...",
  // },
};

const TOKENS = [
  { id: "spacex", solanaMint: "PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh" },
  { id: "anthropic", solanaMint: "Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw" },
  { id: "openai", solanaMint: "PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF" },
  { id: "anduril", solanaMint: "PresTj4Yc2bAR197Er7wz4UUKSfqt6FryBEdAriBoQB" },
  { id: "kalshi", solanaMint: "PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua" },
  { id: "polymarket", solanaMint: "Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP" },
  { id: "xai", solanaMint: "PreC1KtJ1sBPPqaeeqL6Qb15GTLCYVvyYEwxhdfTwfx" },
];

function updateDeploymentConfig(tokenId: string, polygonAddress: string): void {
  const configPath = path.join(
    process.cwd(),
    "deployments",
    tokenId,
    "deployment.json"
  );

  if (!fs.existsSync(configPath)) {
    console.log(`  Skipping ${tokenId}: deployment.json not found`);
    return;
  }

  const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
  config.chains.Polygon.token = polygonAddress;
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
  console.log(`  Updated ${tokenId}/deployment.json`);
}

function generateTokensUpdate(): string {
  const entries = TOKENS.map((token) => {
    const deployed = DEPLOYED_ADDRESSES[token.id];
    const polygonAddress = deployed?.polygonAddress ?? "null";
    return `  ${token.id}: {
    id: "${token.id}",
    name: "${token.id.charAt(0).toUpperCase() + token.id.slice(1)}",
    symbol: "v${token.id.toUpperCase()}",
    solanaMint: "${token.solanaMint}",
    polygonAddress: ${polygonAddress === "null" ? "null" : `"${polygonAddress}"`},
    decimals: 8,
  },`;
  }).join("\n");

  return `// Auto-generated by scripts/update-addresses.ts
export const PRESTOCK_TOKENS = {
${entries}
} as const;`;
}

function main(): void {
  console.log("PreStock Bridge Address Updater");
  console.log("================================\n");

  const deployedCount = Object.keys(DEPLOYED_ADDRESSES).length;

  if (deployedCount === 0) {
    console.log("No addresses to update. Edit DEPLOYED_ADDRESSES in this script first.\n");
    console.log("After deploying contracts, add entries like:");
    console.log(`
DEPLOYED_ADDRESSES = {
  spacex: {
    polygonAddress: "0x...",
    nttManager: "0x...",
    custodyAccount: "...",
  },
  // ...
};
`);
    return;
  }

  console.log(`Updating addresses for ${deployedCount} token(s)...\n`);

  // Update deployment configs
  console.log("Updating deployment configs:");
  for (const [tokenId, addresses] of Object.entries(DEPLOYED_ADDRESSES)) {
    updateDeploymentConfig(tokenId, addresses.polygonAddress);
  }

  // Generate tokens.ts update
  console.log("\nGenerated tokens.ts update:");
  console.log("-".repeat(50));
  console.log(generateTokensUpdate());
  console.log("-".repeat(50));

  console.log("\nTo apply:");
  console.log("1. Copy the generated code above to packages/sdk/src/tokens.ts");
  console.log("2. Update NTT_CUSTODY_ACCOUNTS in packages/sdk/src/monitoring/cli.ts");
  console.log("3. Run: pnpm --filter @vaulto/bridge-sdk build");
}

main();
